# Database Connection Settings
spring.datasource.url=jdbc:postgresql://localhost:5432/seedling_db
spring.datasource.username=postgres
spring.datasource.password=Think@withGeeky!
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate Properties
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Server Configuration
server.port=8080

# Enable Scheduled Tasks Thread Pool Size
spring.task.scheduling.pool.size=2

# Caffeine Cache Configuration
spring.cache.type=caffeine
spring.cache.caffeine.spec=maximumSize=500,recordStats

finnhub.api.key=d8u0e89r01qinhueuqn0d8u0e89r01qinhueuqng
finnhub.base.url=https://finnhub.io/api/v1
